# Site settings
title: Real-life room escape Games
email: guillaume.dedrie@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    A blog about real-life room escape!
baseurl: "/rlreg-blog" # the subpath of your site, e.g. /blog/
url: "https://guillaumededrie.github.io/" # the base hostname & protocol for your site
twitter_username: guillaumededrie
github_username:  guillaumededrie

# Build settings
markdown: kramdown
